### ISSUE TITLE
`connect` may wrongly detect a factory function in `mapStateToProps`

### ISSUE THREAD

**Issue by mraerino** [Festify/fit-html#10]
Will specify later...

**Comment by NeoLegends** [comment]
Hmm?

**Comment by mraerino** [comment]
it's just a little unclear there is a factory method possible there. When bootstrapping a project I just used an empty arrow function which led to weird effect. Would need good docs.

**Comment by NeoLegends** [comment]
We should take a look at how react-redux solves the doc problem and how they determine whether a factory function is present.
